name: 'mir'

version: 1.0.0
config-version: 2

profile: mir

model-paths: ["models"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  mir: 
    +database: analytics
    metadata:
      +materialized: incremental
      +schema: metadata
    emendas_dbt:
      +materialized: table
      +schema: emendas
    dados_abertos_dbt:
     +materialized: table
     +schema: dados_abertos
    empenhos_ted_dbt:
     +materialized: table
     +schema: siafi_dbt
    siconv_dbt:
      +materialized: table
      +schema: siconv_dbt



on-run-start:
  - '{{create_udfs()}}'