version: 2

sources:
  - name: transferegov_emendas
    schema: transferegov_emendas
    tables:
      - name: programas_especiais
      - name: planos_acao_especiais
      - name: empenhos_especiais
      - name: ordens_bancarias_especiais
      - name: historico_pagamentos_especiais
      - name: plano_trabalho_especial
      - name: documentos_habeis_especiais
      - name: relatorio_gestao_especial
      - name: relatorios_gestao_novo_especial
      - name: executor_especial
      - name: metas_especiais
      - name: finalidades_especiais

  - name: camara_deputados
    schema: camara_deputados
    tables: 
      - name: deputados

  - name: senado_federal
    schema: senado_federal
    tables:
      - name: senadores

  - name: transfere_gov
    schema: transfere_gov
    tables:
      - name: programacao_financeira

  - name: siafi
    schema: siafi
    tables:
        - name: ne_tesouro
        - name: ne_tesouro_emendas
        - name: nc_tesouro_pos__2026
        - name: nc_tesouro_pre_2026
        - name: pf_tesouro
        - name: programacao_acao_ptres
